sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start!!"
  - docker build -t react/dev -f Dockerfile.dev .

script:
  - docker run -e CI=true react/dev npm test -- --coverage

after_success:
  - echo "Test Success"

deploy:
  provider: "elasticbeanstalk"
  region: "ap-northeast-2"
  app: "sttv4303Reactapp"
  env: "Sttv4303reactapp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-545770800594"
  bucket_path: "sttv4303Reactapp"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  
